// Seed data for the nihongo study app.
// Designed to be easy to expand later — every entry is a flat object.

// ── VOCAB CLASSES ──────────────────────────────────────────────────────
// Top-level grouping. Each class holds a set of related books (categories).
// Books with `pages: []` render a placeholder — they reserve their slot in
// the UI before content lands.
const HOME_BOOKS = [
  {
    id: 'bathroom',
    titleJa: 'よくしつ',
    titleEn: 'Bathroom',
    glyph: '浴',
    primaryLevel: 'N5',
    pages: [
      {
        id: 'sheet-1',
        type: 'cheatsheet',
        title: 'よくしつ の ことば',
        subtitle: 'Bathroom & washroom — words for the space',
        // image-slot id; user drops the watercolor cheatsheet here
        imageSlotId: 'sheet-bathroom-1',
        items: [
          { num:1,  kanji:'浴室',              kana:'よくしつ',           en:'bathroom' },
          { num:2,  kanji:'鏡',                kana:'かがみ',             en:'mirror' },
          { num:3,  kanji:'洗面台',            kana:'せんめんだい',       en:'washbasin / vanity' },
          { num:4,  kanji:'蛇口',              kana:'じゃぐち',           en:'faucet / tap' },
          { num:5,  kanji:'シャワー',          kana:'しゃわー',           en:'shower' },
          { num:6,  kanji:'浴槽',              kana:'よくそう',           en:'bathtub' },
          { num:7,  kanji:'トイレ',            kana:'といれ',             en:'toilet' },
          { num:8,  kanji:'トイレットペーパー',kana:'といれっとぺーぱー', en:'toilet paper' },
          { num:9,  kanji:'バスマット',        kana:'ばすまっと',         en:'bath mat' },
          { num:10, kanji:'タオル',            kana:'たおる',             en:'towel' },
          { num:11, kanji:'ドア',              kana:'どあ',               en:'door' },
          { num:12, kanji:'窓',                kana:'まど',               en:'window' },
        ]
      },
      {
        id: 'sheet-2',
        type: 'cheatsheet',
        title: 'せんめんだい の ことば',
        subtitle: 'At the sink — closer look',
        imageSlotId: 'sheet-bathroom-2',
        items: [
          { num:1,  kanji:'洗面台',     kana:'せんめんだい',     en:'washbasin' },
          { num:2,  kanji:'鏡',         kana:'かがみ',           en:'mirror' },
          { num:3,  kanji:'蛇口',       kana:'じゃぐち',         en:'faucet' },
          { num:4,  kanji:'液体せっけん',kana:'えきたいせっけん', en:'liquid soap' },
          { num:5,  kanji:'歯ブラシ',   kana:'はぶらし',         en:'toothbrush' },
          { num:6,  kanji:'歯みがき粉', kana:'はみがきこ',       en:'toothpaste' },
          { num:7,  kanji:'コップ',     kana:'こっぷ',           en:'cup' },
          { num:8,  kanji:'ハンドタオル',kana:'はんどたおる',     en:'hand towel' },
          { num:9,  kanji:'くし',       kana:'くし',             en:'comb' },
          { num:10, kanji:'せっけん',   kana:'せっけん',         en:'soap bar' },
          { num:11, kanji:'ドライヤー', kana:'どらいやー',       en:'hair dryer' },
        ]
      },
      {
        id: 'usage',
        type: 'usage',
        title: 'つかいかた',
        subtitle: 'How these words show up in everyday actions',
        items: [
          { ja:'手を洗う',          kana:'てを あらう',          en:'to wash hands' },
          { ja:'シャワーを浴びる',  kana:'しゃわーを あびる',    en:'to take a shower' },
          { ja:'お風呂に入る',      kana:'おふろに はいる',      en:'to take a bath' },
          { ja:'歯を磨く',          kana:'はを みがく',          en:'to brush teeth' },
          { ja:'顔を洗う',          kana:'かおを あらう',        en:'to wash face' },
          { ja:'髪を乾かす',        kana:'かみを かわかす',      en:'to dry hair' },
          { ja:'タオルで体を拭く',  kana:'たおるで からだを ふく',en:'to dry off with a towel' },
          { ja:'鏡を見る',          kana:'かがみを みる',        en:'to look in the mirror' },
          { ja:'蛇口をひねる',      kana:'じゃぐちを ひねる',    en:'to turn the faucet' },
          { ja:'窓を開ける',        kana:'まどを あける',        en:'to open the window' },
        ]
      },
      {
        id: 'sentences',
        type: 'sentences',
        title: 'ぶん',
        subtitle: 'In sentences — start with N5, see more as you grow',
        items: [
          { ja:'食べる 前に、手を 洗います。',
            en:'I wash my hands before eating.', level:'N5' },
          { ja:'毎日 シャワーを 浴びます。',
            en:'I take a shower every day.', level:'N5' },
          { ja:'歯を 磨いてから 寝ます。',
            en:'After brushing my teeth, I go to sleep.', level:'N5' },
          { ja:'タオルで 顔を 拭いて ください。',
            en:'Please dry your face with the towel.', level:'N5' },
          { ja:'寒い 時、人は あまり シャワーを 浴びません。',
            en:"When it's cold, people don't shower much.", level:'N4' },
          { ja:'でも、それは よくないかも しれませんね。',
            en:"But maybe that's not such a good thing, you know?", level:'N4' },
          { ja:'お風呂の あとで、髪を 乾かします。',
            en:'After the bath, I dry my hair.', level:'N4' },
          { ja:'鏡を 見て、髪を 整えました。',
            en:'I looked in the mirror and fixed my hair.', level:'N4' },
          { ja:'窓を 開けると、新鮮な 空気が 入って きます。',
            en:'When you open the window, fresh air comes in.', level:'N3' },
          { ja:'毎朝、洗面台で 顔を 洗うのが 一日の はじまりです。',
            en:'Every morning, washing my face at the sink is how the day begins.', level:'N3' },
          { ja:'蛇口を 閉め忘れない ように 気を つけて ください。',
            en:'Please be careful not to forget to turn off the faucet.', level:'N3' },
          { ja:'湿気の せいで、鏡が くもって しまいました。',
            en:'Because of the humidity, the mirror has fogged up.', level:'N2' },
        ]
      },
    ]
  },
  {
    id: 'kitchen',
    titleJa: 'だいどころ',
    titleEn: 'Kitchen',
    glyph: '台',
    primaryLevel: 'N5',
    pages: [
      {
        id: 'sheet-1',
        type: 'cheatsheet',
        title: 'だいどころ の ことば',
        subtitle: 'In the kitchen',
        imageSlotId: 'sheet-kitchen-1',
        items: [
          { num:1,  kanji:'冷蔵庫',     kana:'れいぞうこ',  en:'refrigerator' },
          { num:2,  kanji:'電子レンジ', kana:'でんしれんじ',en:'microwave' },
          { num:3,  kanji:'コンロ',     kana:'こんろ',      en:'stovetop' },
          { num:4,  kanji:'鍋',         kana:'なべ',        en:'pot' },
          { num:5,  kanji:'フライパン', kana:'ふらいぱん',  en:'frying pan' },
          { num:6,  kanji:'包丁',       kana:'ほうちょう',  en:'kitchen knife' },
          { num:7,  kanji:'まな板',     kana:'まないた',    en:'cutting board' },
          { num:8,  kanji:'お皿',       kana:'おさら',      en:'plate' },
          { num:9,  kanji:'コップ',     kana:'こっぷ',      en:'cup / glass' },
          { num:10, kanji:'箸',         kana:'はし',        en:'chopsticks' },
        ]
      },
      {
        id: 'usage',
        type: 'usage',
        title: 'つかいかた',
        subtitle: 'Doing things in the kitchen',
        items: [
          { ja:'ご飯を作る',   kana:'ごはんを つくる', en:'to cook a meal' },
          { ja:'お皿を洗う',   kana:'おさらを あらう', en:'to wash dishes' },
          { ja:'野菜を切る',   kana:'やさいを きる',   en:'to cut vegetables' },
          { ja:'お湯を沸かす', kana:'おゆを わかす',   en:'to boil water' },
          { ja:'冷蔵庫を開ける',kana:'れいぞうこを あける',en:'to open the fridge' },
        ]
      },
      {
        id: 'sentences',
        type: 'sentences',
        title: 'ぶん',
        subtitle: 'Sentences in the kitchen',
        items: [
          { ja:'毎晩、母が ご飯を 作ります。',  en:'Every night, my mother cooks dinner.', level:'N5' },
          { ja:'お皿を 洗って ください。',     en:'Please wash the dishes.', level:'N5' },
          { ja:'冷蔵庫に 何も ありません。',   en:"There's nothing in the fridge.", level:'N5' },
          { ja:'包丁は 危ない から、気を つけて。',en:"Knives are dangerous, so be careful.", level:'N4' },
          { ja:'お湯が 沸いたら、麺を 入れて ください。',en:'When the water boils, add the noodles.', level:'N4' },
          { ja:'残った 料理は 冷蔵庫に しまって おきましょう。',en:'Let’s put the leftover food away in the fridge.', level:'N3' },
        ]
      }
    ]
  },
  {
    id: 'livingroom',
    titleJa: 'いま',
    titleEn: 'Living Room',
    glyph: '居',
    primaryLevel: 'N5',
    pages: [
      {
        id: 'sheet-1',
        type: 'cheatsheet',
        title: 'いま の ことば',
        subtitle: 'In the living room',
        imageSlotId: 'sheet-livingroom-1',
        items: [
          { num:1,  kanji:'ソファ',     kana:'そふぁ',      en:'sofa' },
          { num:2,  kanji:'テーブル',   kana:'てーぶる',    en:'table' },
          { num:3,  kanji:'テレビ',     kana:'てれび',      en:'television' },
          { num:4,  kanji:'本棚',       kana:'ほんだな',    en:'bookshelf' },
          { num:5,  kanji:'カーテン',   kana:'かーてん',    en:'curtain' },
          { num:6,  kanji:'絨毯',       kana:'じゅうたん',  en:'rug / carpet' },
          { num:7,  kanji:'クッション', kana:'くっしょん',  en:'cushion' },
          { num:8,  kanji:'時計',       kana:'とけい',      en:'clock' },
          { num:9,  kanji:'ランプ',     kana:'らんぷ',      en:'lamp' },
          { num:10, kanji:'植木鉢',     kana:'うえきばち',  en:'potted plant' },
        ]
      },
      {
        id: 'usage',
        type: 'usage',
        title: 'つかいかた',
        subtitle: 'Spending time in the living room',
        items: [
          { ja:'テレビを見る',     kana:'てれびを みる',    en:'to watch TV' },
          { ja:'ソファに座る',     kana:'そふぁに すわる',  en:'to sit on the sofa' },
          { ja:'本を読む',         kana:'ほんを よむ',      en:'to read a book' },
          { ja:'カーテンを閉める', kana:'かーてんを しめる',en:'to close the curtain' },
          { ja:'お茶を飲む',       kana:'おちゃを のむ',    en:'to drink tea' },
        ]
      },
      {
        id: 'sentences',
        type: 'sentences',
        title: 'ぶん',
        subtitle: 'Living-room sentences',
        items: [
          { ja:'ソファで 休んで います。',  en:"I'm resting on the sofa.", level:'N5' },
          { ja:'テレビを 見ても いいですか？',en:'Can I watch TV?', level:'N5' },
          { ja:'夜は、カーテンを 閉めます。',en:'At night, I close the curtains.', level:'N5' },
          { ja:'時々、本を 読みながら お茶を 飲みます。',en:'Sometimes I drink tea while reading.', level:'N4' },
          { ja:'部屋を きれいに してから、友達を 呼びました。',en:'After cleaning the room, I invited friends over.', level:'N3' },
        ]
      }
    ]
  },
  {
    id: 'bedroom',
    titleJa: 'しんしつ',
    titleEn: 'Bedroom',
    glyph: '寝',
    primaryLevel: 'N5',
    pages: [
      {
        id: 'sheet-1',
        type: 'cheatsheet',
        title: 'しんしつ の ことば',
        subtitle: 'In the bedroom',
        imageSlotId: 'sheet-bedroom-1',
        items: [
          { num:1,  kanji:'ベッド',     kana:'べっど',      en:'bed' },
          { num:2,  kanji:'枕',         kana:'まくら',      en:'pillow' },
          { num:3,  kanji:'布団',       kana:'ふとん',      en:'futon / duvet' },
          { num:4,  kanji:'目覚まし時計',kana:'めざましどけい',en:'alarm clock' },
          { num:5,  kanji:'クローゼット',kana:'くろーぜっと',en:'closet' },
          { num:6,  kanji:'引き出し',   kana:'ひきだし',    en:'drawer' },
          { num:7,  kanji:'鏡',         kana:'かがみ',      en:'mirror' },
          { num:8,  kanji:'スタンド',   kana:'すたんど',    en:'bedside lamp' },
          { num:9,  kanji:'カーテン',   kana:'かーてん',    en:'curtain' },
        ]
      },
      {
        id: 'usage',
        type: 'usage',
        title: 'つかいかた',
        subtitle: 'Going to bed / waking up',
        items: [
          { ja:'寝る',           kana:'ねる',           en:'to sleep / go to bed' },
          { ja:'起きる',         kana:'おきる',         en:'to wake up' },
          { ja:'目覚ましをかける',kana:'めざましを かける',en:'to set the alarm' },
          { ja:'布団をたたむ',   kana:'ふとんを たたむ',en:'to fold up the futon' },
        ]
      },
      {
        id: 'sentences',
        type: 'sentences',
        title: 'ぶん',
        subtitle: 'Bedroom sentences',
        items: [
          { ja:'十時に 寝ます。',          en:'I go to bed at 10.', level:'N5' },
          { ja:'目覚ましを 七時に かけました。',en:'I set the alarm for 7.', level:'N5' },
          { ja:'なかなか 眠れません。',    en:"I can't really get to sleep.", level:'N4' },
          { ja:'寝る 前に、本を 少し 読みます。',en:'Before bed, I read a little.', level:'N4' },
        ]
      }
    ]
  },
  {
    id: 'entrance',
    titleJa: 'げんかん',
    titleEn: 'Entrance',
    glyph: '玄',
    primaryLevel: 'N5',
    pages: [
      {
        id: 'sheet-1',
        type: 'cheatsheet',
        title: 'げんかん の ことば',
        subtitle: 'At the entrance',
        imageSlotId: 'sheet-entrance-1',
        items: [
          { num:1,  kanji:'玄関',     kana:'げんかん',    en:'entryway' },
          { num:2,  kanji:'靴',       kana:'くつ',        en:'shoes' },
          { num:3,  kanji:'スリッパ', kana:'すりっぱ',    en:'slippers' },
          { num:4,  kanji:'傘',       kana:'かさ',        en:'umbrella' },
          { num:5,  kanji:'鍵',       kana:'かぎ',        en:'key' },
          { num:6,  kanji:'郵便受け', kana:'ゆうびんうけ',en:'mailbox' },
          { num:7,  kanji:'ドア',     kana:'どあ',        en:'door' },
        ]
      },
      {
        id: 'usage',
        type: 'usage',
        title: 'つかいかた',
        subtitle: 'Coming and going',
        items: [
          { ja:'靴を脱ぐ', kana:'くつを ぬぐ', en:'to take off shoes' },
          { ja:'靴を履く', kana:'くつを はく', en:'to put on shoes' },
          { ja:'鍵をかける',kana:'かぎを かける',en:'to lock (with a key)' },
          { ja:'家を出る', kana:'いえを でる', en:'to leave the house' },
        ]
      },
      {
        id: 'sentences',
        type: 'sentences',
        title: 'ぶん',
        subtitle: 'Entrance sentences',
        items: [
          { ja:'家に 入る 時、靴を 脱ぎます。', en:"When you enter the house, you take off your shoes.", level:'N5' },
          { ja:'雨が 降って いるから、傘を 持って いきます。',en:"It's raining, so I'll take an umbrella.", level:'N4' },
          { ja:'出かける 前に、鍵を かけるのを 忘れないで ください。',en:"Don't forget to lock the door before going out.", level:'N3' },
        ]
      }
    ]
  },
];

window.VOCAB_CLASSES = [
  {
    id: 'home',
    glyph: '家',
    titleJa: 'いえ',
    titleEn: 'Home',
    pageTitleJa: '部屋ごとに ことばを 集める',
    pageTitleEn: 'Vocabulary, gathered room by room',
    books: HOME_BOOKS,
  },
  {
    id: 'eating-out',
    glyph: '食',
    titleJa: 'がいしょく',
    titleEn: 'Eating Out',
    pageTitleJa: '食べに 出かける',
    pageTitleEn: 'Words for sitting down somewhere',
    books: [
      { id:'sushi-ya', titleJa:'すしや',   titleEn:'Sushi',       glyph:'寿', primaryLevel:'N5', pages:[] },
      { id:'omakase',  titleJa:'おまかせ', titleEn:'Omakase',     glyph:'板', primaryLevel:'N4', pages:[] },
      { id:'izakaya',  titleJa:'いざかや', titleEn:'Izakaya',     glyph:'串', primaryLevel:'N5', pages:[] },
      { id:'ramen-ya', titleJa:'ラーメン', titleEn:'Ramen',       glyph:'麺', primaryLevel:'N5', pages:[] },
      { id:'yatai',    titleJa:'やたい',   titleEn:'Street Food', glyph:'屋', primaryLevel:'N5', pages:[] },
      { id:'konbini',  titleJa:'コンビニ', titleEn:'Conbini',     glyph:'便', primaryLevel:'N5', pages:[] },
    ],
  },
  {
    id: 'stays',
    glyph: '宿',
    titleJa: 'やど',
    titleEn: 'Stays',
    pageTitleJa: '場面ごとに ことばを 集める',
    pageTitleEn: 'Places and scenes — beyond home',
    books: [
      { id:'hotel',  titleJa:'ホテル',   titleEn:'Hotel',       glyph:'宿', primaryLevel:'N5', pages:[] },
      { id:'office', titleJa:'おふぃす', titleEn:'Office',      glyph:'働', primaryLevel:'N4', pages:[] },
      { id:'airbnb', titleJa:'えあびー', titleEn:'Airbnb host', glyph:'貸', primaryLevel:'N3', pages:[] },
      { id:'dorm',   titleJa:'りょう',   titleEn:'Dorm',        glyph:'寮', primaryLevel:'N4', pages:[] },
    ],
  },
];

// Flat list for cross-class lookups (dictionary jumps, popover word lookup).
window.VOCAB_BOOKS = window.VOCAB_CLASSES.flatMap(c => c.books);

// ── FLASHCARDS ─────────────────────────────────────────────────────────
// Cards are grouped into classes. Each class is a focused thematic deck;
// adding more classes is the easiest way to grow the curriculum.
window.FLASHCARD_CLASSES = [
  {
    id: 'basic',
    titleJa: 'きほん',
    titleEn: 'Basic',
    glyph: '一',
    cards: [
      { id:'roof',      kanji:'宀', kun:'うかんむり', on:'',       en:'roof / crown / cap (radical)', strokes:3 },
      { id:'katana',    kanji:'刀', kun:'かたな', on:'トウ',   en:'katana / sword', strokes:2, examples:[{word:'日本刀',reading:'NIHONTŌ',meaning:'Japanese sword'},{word:'刀剣',reading:'TŌKEN',meaning:'swords'},{word:'小刀',reading:'kogatana',meaning:'small knife'}] },
      { id:'power',     kanji:'力', kun:'ちから', on:'リョク', en:'power / strength', strokes:2, examples:[{word:'力持ち',reading:'chikaramochi',meaning:'strong person'},{word:'電力',reading:'DENRYOKU',meaning:'electric power'},{word:'努力',reading:'DORYOKU',meaning:'effort'}] },
      { id:'bow',       kanji:'弓', kun:'ゆみ',   on:'キュウ', en:'bow', strokes:3, examples:[{word:'弓道',reading:'KYŪDŌ',meaning:'archery'},{word:'弓矢',reading:'yumiya',meaning:'bow and arrow'},{word:'弓形',reading:'KYŪKEI',meaning:'arch shape'}] },
      { id:'city',      kanji:'市', kun:'いち',   on:'シ',     en:'market / city', strokes:5, examples:[{word:'市場',reading:'SHIJŌ',meaning:'market'},{word:'市民',reading:'SHIMIN',meaning:'citizen'},{word:'都市',reading:'TOSHI',meaning:'city'}] },
      { id:'ricefield', kanji:'田', kun:'た',     on:'デン',   en:'rice field', strokes:5, examples:[{word:'田んぼ',reading:'tanbo',meaning:'rice paddy'},{word:'田園',reading:'DEN\'EN',meaning:'countryside'},{word:'田植え',reading:'taue',meaning:'rice planting'}] },
      { id:'town',      kanji:'町', kun:'まち',   on:'チョウ', en:'town', strokes:7, examples:[{word:'町中',reading:'machinaka',meaning:'downtown'},{word:'町長',reading:'CHŌCHŌ',meaning:'town mayor'},{word:'町人',reading:'CHŌNIN',meaning:'townspeople'}] },
      { id:'village',   kanji:'村', kun:'むら',   on:'ソン',   en:'village', strokes:7, examples:[{word:'村長',reading:'SONCHŌ',meaning:'village chief'},{word:'村人',reading:'murabito',meaning:'villager'},{word:'村落',reading:'SONRAKU',meaning:'hamlet'}] },
      { id:'king',      kanji:'王', kun:'おう',   on:'オウ',   en:'king', strokes:4, examples:[{word:'王子',reading:'ŌJI',meaning:'prince'},{word:'女王',reading:'JOŌ',meaning:'queen'},{word:'王様',reading:'Ōsama',meaning:'king'}] },
      { id:'life',      kanji:'生', kun:'い',     on:'セイ',   en:'life', strokes:5, examples:[{word:'生活',reading:'SEIKATSU',meaning:'daily life'},{word:'先生',reading:'SENSEI',meaning:'teacher'},{word:'生まれる',reading:'umareru',meaning:'to be born'}] },
      { id:'country',   kanji:'国', kun:'くに',   on:'コク',   en:'country', strokes:8, examples:[{word:'外国',reading:'GAIKOKU',meaning:'foreign country'},{word:'国民',reading:'KOKUMIN',meaning:'citizens'},{word:'国語',reading:'KOKUGO',meaning:'Japanese (subject)'}] },
      { id:'sun',       kanji:'日', kun:'ひ',     on:'ニチ',   en:'sun / day', strokes:4, examples:[{word:'日曜日',reading:'NICHIYŌbi',meaning:'Sunday'},{word:'毎日',reading:'MAINICHI',meaning:'every day'},{word:'日の出',reading:'hinode',meaning:'sunrise'}] },
      { id:'moon',      kanji:'月', kun:'つき',   on:'ゲツ',   en:'moon / month', strokes:4, examples:[{word:'月曜日',reading:'GETSUYŌbi',meaning:'Monday'},{word:'正月',reading:'SHŌGATSU',meaning:'New Year'},{word:'月見',reading:'tsukimi',meaning:'moon viewing'}] },
      { id:'mtn',       kanji:'山', kun:'やま',   on:'サン',   en:'mountain', strokes:3, examples:[{word:'富士山',reading:'FUJISAN',meaning:'Mt. Fuji'},{word:'山道',reading:'yamaji',meaning:'mountain path'},{word:'山火事',reading:'yamakaji',meaning:'wildfire'}] },
      { id:'river',     kanji:'川', kun:'かわ',   on:'セン',   en:'river', strokes:3, examples:[{word:'川上',reading:'kawakami',meaning:'upstream'},{word:'川下',reading:'kawashimo',meaning:'downstream'},{word:'小川',reading:'ogawa',meaning:'stream'}] },
      { id:'big',       kanji:'大', kun:'おお',   on:'ダイ',   en:'big / large', strokes:3, examples:[{word:'大学',reading:'DAIGAKU',meaning:'university'},{word:'大人',reading:'otona',meaning:'adult'},{word:'大きい',reading:'ōkii',meaning:'big'}] },
      { id:'small',     kanji:'小', kun:'ちい',   on:'ショウ', en:'small', strokes:3, examples:[{word:'小学校',reading:'SHŌGAKKŌ',meaning:'elementary school'},{word:'小さい',reading:'chiisai',meaning:'small'},{word:'小鳥',reading:'kotori',meaning:'small bird'}] },
      { id:'yen',       kanji:'円', kun:'まる',   on:'エン',   en:'yen / circle', strokes:4, examples:[{word:'円形',reading:'ENKEI',meaning:'circle'},{word:'円高',reading:'ENdaka',meaning:'strong yen'},{word:'百円',reading:'HYAKUEN',meaning:'100 yen'}] },
      { id:'gold',      kanji:'金', kun:'かね',   on:'キン',   en:'gold / money / metal', strokes:8, examples:[{word:'金曜日',reading:'KIN\'YŌbi',meaning:'Friday'},{word:'お金',reading:'okane',meaning:'money'},{word:'金魚',reading:'kingyo',meaning:'goldfish'}] },
      { id:'jewel',     kanji:'玉', kun:'たま',   on:'ギョク', en:'jewel / ball', strokes:5, examples:[{word:'玉ねぎ',reading:'tamanegi',meaning:'onion'},{word:'目玉',reading:'medama',meaning:'eyeball'},{word:'宝玉',reading:'HŌGYOKU',meaning:'jewel'}] },
      { id:'thread',    kanji:'糸', kun:'いと',   on:'シ',     en:'thread / string', strokes:6, examples:[{word:'毛糸',reading:'keito',meaning:'wool yarn'},{word:'糸口',reading:'itoguchi',meaning:'clue'},{word:'糸巻き',reading:'itomaki',meaning:'spool'}] },
      { id:'vehicle',   kanji:'車', kun:'くるま', on:'シャ',   en:'vehicle / car', strokes:7, examples:[{word:'自動車',reading:'JIDŌSHA',meaning:'car'},{word:'電車',reading:'DENSHA',meaning:'train'},{word:'車輪',reading:'SHARIN',meaning:'wheel'}] },
      { id:'sound',     kanji:'音', kun:'おと',   on:'オン',   en:'sound / noise', strokes:9, examples:[{word:'音楽',reading:'ONGAKU',meaning:'music'},{word:'音声',reading:'ONSEI',meaning:'voice / audio'},{word:'足音',reading:'ashioto',meaning:'footsteps'}] },
      { id:'stand',     kanji:'立', kun:'た',     on:'リツ',   en:'stand / establish', strokes:5, examples:[{word:'立場',reading:'tachiba',meaning:'standpoint'},{word:'独立',reading:'DOKURITSU',meaning:'independence'},{word:'立派',reading:'RIPPA',meaning:'splendid'}] },
    ],
  },
  {
    id: 'people',
    titleJa: 'ひと',
    titleEn: 'People',
    glyph: '人',
    cards: [
      { id:'person', kanji:'人', kun:'ひと',     on:'ジン',   en:'person',
        strokes:2,
        examples:[
          {word:'日本人',reading:'NIHONJIN',meaning:'Japanese person'},
          {word:'大人',reading:'otona',meaning:'adult'},
          {word:'人口',reading:'JINKŌ',meaning:'population'},
        ] },
      { id:'enter',  kanji:'入', kun:'はい',     on:'ニュウ', en:'enter',
        strokes:2,
        examples:[
          {word:'入口',reading:'iriguchi',meaning:'entrance'},
          {word:'入学',reading:'NYŪGAKU',meaning:'enrollment'},
          {word:'入場',reading:'NYŪJŌ',meaning:'admission'},
        ] },
      // female cluster
      { id:'mother', kanji:'母', kun:'はは',     on:'ボ',     en:'mother',
        usage:{ ja:'お母さん', kana:'おかあさん' },
        strokes:5,
        examples:[
          {word:'お母さん',reading:'okaasan',meaning:'mother (polite)'},
          {word:'母国',reading:'BOKOKU',meaning:'motherland'},
          {word:'母音',reading:'BOIN',meaning:'vowel'},
        ] },
      { id:'woman',  kanji:'女', kun:'おんな',   on:'ジョ',   en:'woman',
        strokes:3,
        examples:[
          {word:'女性',reading:'JOSEI',meaning:'woman'},
          {word:'女の子',reading:'onnanoko',meaning:'girl'},
          {word:'女子',reading:'JOSHI',meaning:'girl / woman'},
        ] },
      { id:'oneesan', kanji:'姉', kun:'あね',    on:'シ',     en:'older sister',
        usage:{ ja:'お姉さん', kana:'おねえさん' },
        strokes:8,
        examples:[
          {word:'お姉さん',reading:'onēsan',meaning:'older sister (polite)'},
          {word:'姉妹',reading:'SHIMAI',meaning:'sisters'},
          {word:'義姉',reading:'GISHI',meaning:'sister-in-law'},
        ] },
      { id:'imouto', kanji:'妹', kun:'いもうと', on:'マイ',   en:'younger sister',
        strokes:8,
        examples:[
          {word:'妹さん',reading:'imōtosan',meaning:'younger sister (polite)'},
          {word:'姉妹',reading:'SHIMAI',meaning:'sisters'},
          {word:'義妹',reading:'GIMAI',meaning:'sister-in-law'},
        ] },
      { id:'shimai', kanji:'姉妹', kun:'しまい', on:'シマイ', en:'sisters',
        strokes:16 },
      // male cluster
      { id:'father', kanji:'父', kun:'ちち',     on:'フ',     en:'father',
        usage:{ ja:'お父さん', kana:'おとうさん' },
        strokes:4,
        examples:[
          {word:'お父さん',reading:'otōsan',meaning:'father (polite)'},
          {word:'父母',reading:'FUBO',meaning:'parents'},
          {word:'父親',reading:'chichioya',meaning:'father'},
        ] },
      { id:'man',    kanji:'男', kun:'おとこ',   on:'ダン',   en:'man',
        strokes:7,
        examples:[
          {word:'男性',reading:'DANSEI',meaning:'man'},
          {word:'男の子',reading:'otokonoko',meaning:'boy'},
          {word:'男子',reading:'DANSHI',meaning:'boy / man'},
        ] },
      { id:'oniisan', kanji:'兄', kun:'あに',    on:'ケイ',   en:'older brother',
        usage:{ ja:'お兄さん', kana:'おにいさん' },
        strokes:5,
        examples:[
          {word:'お兄さん',reading:'onīsan',meaning:'older brother (polite)'},
          {word:'兄弟',reading:'KYŌDAI',meaning:'siblings'},
          {word:'兄貴',reading:'aniki',meaning:'big bro'},
        ] },
      { id:'otouto', kanji:'弟', kun:'おとうと', on:'テイ',   en:'younger brother',
        strokes:7,
        examples:[
          {word:'弟子',reading:'DESHI',meaning:'disciple'},
          {word:'兄弟',reading:'KYŌDAI',meaning:'siblings'},
          {word:'弟さん',reading:'otōtosan',meaning:'younger brother (polite)'},
        ] },
      { id:'kyoudai', kanji:'兄弟', kun:'きょうだい', on:'キョウダイ', en:'brothers / siblings',
        strokes:12 },
      // others
      { id:'child',  kanji:'子', kun:'こ',       on:'シ',     en:'child',
        strokes:3,
        examples:[
          {word:'子供',reading:'kodomo',meaning:'children'},
          {word:'女子',reading:'JOSHI',meaning:'girl'},
          {word:'子犬',reading:'koinu',meaning:'puppy'},
        ] },
      { id:'like',   kanji:'好', kun:'す',       on:'コウ',   en:'like / fond',
        strokes:6,
        examples:[
          {word:'好き',reading:'suki',meaning:'like'},
          {word:'好物',reading:'KŌBUTSU',meaning:'favorite food'},
          {word:'好意',reading:'KŌI',meaning:'goodwill'},
        ] },
      { id:'character', kanji:'字', kun:'じ',     on:'ジ',     en:'character / letter',
        seeAlso:['子','宀'],
        strokes:6,
        examples:[
          {word:'文字',reading:'MOJI',meaning:'character'},
          {word:'漢字',reading:'KANJI',meaning:'kanji'},
          {word:'数字',reading:'SŪJI',meaning:'number'},
        ] },
      { id:'write',  kanji:'書', kun:'か',       on:'ショ',   en:'write / book / calligraphy',
        seeAlso:['日','目'],
        strokes:10,
        examples:[
          {word:'読書',reading:'DOKUSHO',meaning:'reading books'},
          {word:'書道',reading:'SHODŌ',meaning:'calligraphy'},
          {word:'書く',reading:'kaku',meaning:'to write'},
        ] },
      { id:'friend', kanji:'友', kun:'とも',     on:'ユウ',   en:'friend',
        strokes:4,
        examples:[
          {word:'友達',reading:'tomodachi',meaning:'friend'},
          {word:'友人',reading:'YŪJIN',meaning:'friend (formal)'},
          {word:'友好',reading:'YŪKŌ',meaning:'friendship'},
        ] },
      { id:'anti',   kanji:'反', kun:'そら',     on:'ハン',   en:'anti- / opposite',
        strokes:4,
        examples:[
          {word:'反対',reading:'HANTAI',meaning:'opposite'},
          {word:'反省',reading:'HANSEI',meaning:'reflection'},
          {word:'反応',reading:'HANNŌ',meaning:'reaction'},
        ] },
      { id:'rest',   kanji:'休', kun:'やす',     on:'キュウ', en:'rest / holiday',
        seeAlso:['人','木'],
        strokes:6,
        examples:[
          {word:'休日',reading:'KYŪJITSU',meaning:'holiday'},
          {word:'休憩',reading:'KYŪKEI',meaning:'break'},
          {word:'休み',reading:'yasumi',meaning:'rest / day off'},
        ] },
    ],
  },
  {
    id: 'nature',
    titleJa: 'しぜん',
    titleEn: 'Nature',
    glyph: '自',
    cards: [
      // elements lead Nature: fire, water, ice, then earth + leave/past
      { id:'fire',     kanji:'火', kun:'ひ',     on:'カ',     en:'fire',
        strokes:4, examples:[{word:'火曜日',reading:'KAYŌbi',meaning:'Tuesday'},{word:'火山',reading:'KAZAN',meaning:'volcano'},{word:'火花',reading:'hibana',meaning:'spark'}] },
      { id:'water',    kanji:'水', kun:'みず',   on:'スイ',   en:'water',
        strokes:4, examples:[{word:'水曜日',reading:'SUIYŌbi',meaning:'Wednesday'},{word:'水泳',reading:'SUIEI',meaning:'swimming'},{word:'水着',reading:'mizugi',meaning:'swimsuit'}] },
      { id:'ice',      kanji:'氷', kun:'こおり', on:'ヒョウ', en:'ice',
        strokes:5, examples:[{word:'氷山',reading:'HYŌZAN',meaning:'iceberg'},{word:'氷点',reading:'HYŌTEN',meaning:'freezing point'},{word:'氷水',reading:'kōrimizu',meaning:'ice water'}] },
      { id:'tree',     kanji:'木', kun:'き',     on:'ボク',   en:'tree / wood',
        strokes:4, examples:[{word:'木曜日',reading:'MOKUYŌbi',meaning:'Thursday'},{word:'木造',reading:'MOKUZŌ',meaning:'wooden'},{word:'木陰',reading:'kokage',meaning:'tree shade'}] },
      { id:'book',     kanji:'本', kun:'もと',   on:'ホン',   en:'book / origin / root',
        strokes:5, examples:[{word:'日本',reading:'NIHON',meaning:'Japan'},{word:'本当',reading:'HONTŌ',meaning:'really'},{word:'本棚',reading:'hondana',meaning:'bookshelf'}] },
      { id:'earth',    kanji:'土', kun:'つち',   on:'ド',     en:'earth / soil / Saturday',
        strokes:3, examples:[{word:'土曜日',reading:'DOYŌbi',meaning:'Saturday'},{word:'土地',reading:'TOCHI',meaning:'land'},{word:'土産',reading:'miyage',meaning:'souvenir'}] },
      { id:'leave',    kanji:'去', kun:'さる',   on:'キョ',   en:'to leave / past',
        strokes:5, examples:[{word:'去年',reading:'KYONEN',meaning:'last year'},{word:'過去',reading:'KAKO',meaning:'the past'},{word:'去る',reading:'saru',meaning:'to leave'}] },
      // wood family + the not-yet/insect lead-in
      { id:'woods',    kanji:'林', kun:'はやし', on:'リン',   en:'woods',
        strokes:8, examples:[{word:'林道',reading:'RINDŌ',meaning:'forest road'},{word:'山林',reading:'SANRIN',meaning:'mountain forest'},{word:'林業',reading:'RINGYŌ',meaning:'forestry'}] },
      { id:'forest',   kanji:'森', kun:'もり',   on:'シン',   en:'forest',
        strokes:12, examples:[{word:'森林',reading:'SHINRIN',meaning:'forest'},{word:'森林浴',reading:'SHINRINYOKU',meaning:'forest bathing'},{word:'森の中',reading:'morinonaka',meaning:'in the forest'}] },
      { id:'cliff',    kanji:'厂', kun:'がけ',   on:'カン',   en:'cliff (radical)',
        strokes:2 },
      { id:'stone',    kanji:'石', kun:'いし',   on:'セキ',   en:'stone / rock',
        strokes:5, examples:[{word:'石油',reading:'SEKIYU',meaning:'petroleum'},{word:'宝石',reading:'HŌSEKI',meaning:'jewel'},{word:'石橋',reading:'ishibashi',meaning:'stone bridge'}] },
      { id:'rock',     kanji:'岩', kun:'いわ',   on:'ガン',   en:'rock / boulder',
        strokes:8, examples:[{word:'岩石',reading:'GANSEKI',meaning:'rock'},{word:'岩山',reading:'iwayama',meaning:'rocky mountain'},{word:'溶岩',reading:'YŌGAN',meaning:'lava'}] },
      { id:'cave',     kanji:'宕', kun:'ほら',   on:'トウ',   en:'cave',
        strokes:8, seeAlso:['宀','石'] },
      { id:'mada',     kanji:'未', kun:'まだ',   on:'ミ',     en:'not yet / unripe',
        strokes:5, examples:[{word:'未来',reading:'MIRAI',meaning:'future'},{word:'未知',reading:'MICHI',meaning:'unknown'},{word:'未定',reading:'MITEI',meaning:'undecided'}],
        seeAlso:['妹'] },
      { id:'insect',   kanji:'虫', kun:'むし',   on:'チュウ', en:'insect · bichinho (pt)',
        strokes:6, examples:[{word:'虫歯',reading:'mushiba',meaning:'cavity'},{word:'昆虫',reading:'KONCHŪ',meaning:'insect'},{word:'害虫',reading:'GAICHŪ',meaning:'pest'}] },
      // seasons (N5)
      { id:'spring',   kanji:'春', kun:'はる',   on:'シュン', en:'spring',
        strokes:9, examples:[{word:'春分',reading:'SHUNBUN',meaning:'spring equinox'},{word:'春休み',reading:'haruyasumi',meaning:'spring break'},{word:'青春',reading:'SEISHUN',meaning:'youth'}] },
      { id:'summer',   kanji:'夏', kun:'なつ',   on:'カ',     en:'summer',
        strokes:10, examples:[{word:'夏休み',reading:'natsuyasumi',meaning:'summer break'},{word:'夏至',reading:'GESHI',meaning:'summer solstice'},{word:'真夏',reading:'manatsu',meaning:'midsummer'}] },
      { id:'autumn',   kanji:'秋', kun:'あき',   on:'シュウ', en:'autumn',
        strokes:9, examples:[{word:'秋分',reading:'SHŪBUN',meaning:'autumn equinox'},{word:'秋風',reading:'akikaze',meaning:'autumn breeze'},{word:'秋田',reading:'AKITA',meaning:'Akita'}] },
      { id:'winter',   kanji:'冬', kun:'ふゆ',   on:'トウ',   en:'winter',
        strokes:5, examples:[{word:'冬休み',reading:'fuyuyasumi',meaning:'winter break'},{word:'冬至',reading:'TŌJI',meaning:'winter solstice'},{word:'冬眠',reading:'TŌMIN',meaning:'hibernation'}] },
      // weather
      { id:'rain',     kanji:'雨', kun:'あめ',   on:'ウ',     en:'rain',
        strokes:8, examples:[{word:'梅雨',reading:'TSUYU',meaning:'rainy season'},{word:'大雨',reading:'ōame',meaning:'heavy rain'},{word:'雨水',reading:'amamizu',meaning:'rainwater'}] },
      { id:'umbrella', kanji:'傘', kun:'かさ',   on:'サン',   en:'umbrella',
        strokes:12, examples:[{word:'傘立て',reading:'kasatate',meaning:'umbrella stand'},{word:'雨傘',reading:'amagasa',meaning:'rain umbrella'},{word:'日傘',reading:'higasa',meaning:'parasol'}] },
      { id:'wind',     kanji:'風', kun:'かぜ',   on:'フウ',   en:'wind',
        strokes:9, examples:[{word:'台風',reading:'TAIFŪ',meaning:'typhoon'},{word:'風景',reading:'FŪKEI',meaning:'scenery'},{word:'風邪',reading:'kaze',meaning:'cold (illness)'}] },
      { id:'sky',      kanji:'空', kun:'そら',   on:'クウ',   en:'sky',
        strokes:8, examples:[{word:'空気',reading:'KŪKI',meaning:'air'},{word:'空港',reading:'KŪKŌ',meaning:'airport'},{word:'空色',reading:'sorairo',meaning:'sky blue'}] },
      { id:'flower',   kanji:'花', kun:'はな',   on:'カ',     en:'flower',
        strokes:7, examples:[{word:'花火',reading:'hanabi',meaning:'fireworks'},{word:'花見',reading:'hanami',meaning:'flower viewing'},{word:'生け花',reading:'ikebana',meaning:'flower arrangement'}] },
      { id:'snow',     kanji:'雪', kun:'ゆき',   on:'セツ',   en:'snow',
        strokes:11, examples:[{word:'雪だるま',reading:'yukidaruma',meaning:'snowman'},{word:'大雪',reading:'ōyuki',meaning:'heavy snow'},{word:'雪国',reading:'yukiguni',meaning:'snow country'}] },
      { id:'cloud',    kanji:'雲', kun:'くも',   on:'ウン',   en:'cloud',
        strokes:12, examples:[{word:'雨雲',reading:'amagumo',meaning:'rain cloud'},{word:'入道雲',reading:'nyūdōgumo',meaning:'cumulonimbus'},{word:'雲海',reading:'UNKAI',meaning:'sea of clouds'}] },
      { id:'star',     kanji:'星', kun:'ほし',   on:'セイ',   en:'star',
        strokes:9, examples:[{word:'星座',reading:'SEIZA',meaning:'constellation'},{word:'流れ星',reading:'nagareboshi',meaning:'shooting star'},{word:'星空',reading:'hoshizora',meaning:'starry sky'}] },
      { id:'leaf',     kanji:'葉', kun:'は',     on:'ヨウ',   en:'leaf',
        strokes:12, examples:[{word:'言葉',reading:'kotoba',meaning:'word'},{word:'葉書',reading:'hagaki',meaning:'postcard'},{word:'紅葉',reading:'KŌYŌ',meaning:'autumn leaves'}] },
      { id:'grass',    kanji:'草', kun:'くさ',   on:'ソウ',   en:'grass',
        strokes:9, examples:[{word:'草原',reading:'SŌGEN',meaning:'grassland'},{word:'草花',reading:'kusabana',meaning:'wildflower'},{word:'雑草',reading:'ZASSŌ',meaning:'weed'}] },
      { id:'bamboo',   kanji:'竹', kun:'たけ',   on:'チク',   en:'bamboo',
        strokes:6, examples:[{word:'竹林',reading:'CHIKURIN',meaning:'bamboo grove'},{word:'竹の子',reading:'takenoko',meaning:'bamboo shoot'},{word:'竹馬',reading:'takeuma',meaning:'stilts'}] },
      { id:'dog',      kanji:'犬', kun:'いぬ',   on:'ケン',   en:'dog',
        strokes:4, examples:[{word:'猟犬',reading:'RYŌKEN',meaning:'hunting dog'},{word:'犬小屋',reading:'inugoya',meaning:'kennel'},{word:'子犬',reading:'koinu',meaning:'puppy'}],
        seeAlso:['大'] },
      { id:'shell',    kanji:'貝', kun:'かい',   on:'バイ',   en:'shell / shellfish',
        strokes:7, examples:[{word:'貝殻',reading:'kaigara',meaning:'seashell'},{word:'貝柱',reading:'kaibashira',meaning:'scallop'},{word:'巻き貝',reading:'makigai',meaning:'snail'}] },
      { id:'spirit',   kanji:'気', kun:'き',     on:'キ',     en:'spirit / air / energy',
        strokes:6, examples:[{word:'天気',reading:'TENKI',meaning:'weather'},{word:'元気',reading:'GENKI',meaning:'energetic'},{word:'気持ち',reading:'kimochi',meaning:'feeling'}] },
    ],
  },
  {
    id: 'body',
    titleJa: 'からだ',
    titleEn: 'Body',
    glyph: '体',
    // Basic-first within thematic clusters. The 目見自首 cluster sits
    // together right after the eye — they all share the rectangular 目
    // component as a visual hook, even though their meanings diverge.
    cards: [
      { id:'body',  kanji:'体', kun:'からだ',   on:'タイ', en:'body',
        strokes:7,
        examples:[
          {word:'体育',reading:'TAIIKU',meaning:'physical education'},
          {word:'体力',reading:'TAIRYOKU',meaning:'stamina'},
          {word:'体温',reading:'TAION',meaning:'body temperature'},
        ] },
      { id:'hand',  kanji:'手', kun:'て',       on:'シュ', en:'hand',
        strokes:4,
        examples:[
          {word:'手紙',reading:'tegami',meaning:'letter'},
          {word:'握手',reading:'AKUSHU',meaning:'handshake'},
          {word:'手話',reading:'SHUWA',meaning:'sign language'},
        ] },
      // 目 cluster — same eye-radical shape
      { id:'eye',   kanji:'目', kun:'め',       on:'モク', en:'eye',
        strokes:5,
        examples:[
          {word:'目的',reading:'MOKUTEKI',meaning:'purpose'},
          {word:'目玉',reading:'medama',meaning:'eyeball'},
          {word:'目覚まし',reading:'mezamashi',meaning:'alarm clock'},
        ] },
      { id:'look',  kanji:'見', kun:'み',       on:'ケン', en:'look / see',
        strokes:7,
        examples:[
          {word:'見学',reading:'KENGAKU',meaning:'field trip'},
          {word:'花見',reading:'hanami',meaning:'flower viewing'},
          {word:'見本',reading:'mihon',meaning:'sample'},
        ] },
      { id:'self',  kanji:'自', kun:'みずから', on:'ジ',   en:'self / oneself',
        usage:{ ja:'自分', kana:'じぶん' },
        strokes:6,
        examples:[
          {word:'自分',reading:'JIBUN',meaning:'oneself'},
          {word:'自然',reading:'SHIZEN',meaning:'nature'},
          {word:'自転車',reading:'JITENSHA',meaning:'bicycle'},
        ] },
      { id:'neck',  kanji:'首', kun:'くび',     on:'シュ', en:'neck',
        strokes:9,
        examples:[
          {word:'首都',reading:'SHUTO',meaning:'capital city'},
          {word:'首相',reading:'SHUSHŌ',meaning:'prime minister'},
          {word:'手首',reading:'tekubi',meaning:'wrist'},
        ] },
      // other body parts
      { id:'mouth', kanji:'口', kun:'くち',     on:'コウ', en:'mouth / opening / entrance',
        strokes:3,
        examples:[
          {word:'入口',reading:'iriguchi',meaning:'entrance'},
          {word:'人口',reading:'JINKŌ',meaning:'population'},
          {word:'口紅',reading:'kuchibeni',meaning:'lipstick'},
        ] },
      { id:'ear',   kanji:'耳', kun:'みみ',     on:'ジ',   en:'ear',
        strokes:6,
        examples:[
          {word:'耳鳴り',reading:'miminari',meaning:'ringing in ears'},
          {word:'耳元',reading:'mimimoto',meaning:'near one\'s ear'},
          {word:'早耳',reading:'hayamimi',meaning:'sharp ears'},
        ] },
      { id:'foot',  kanji:'足', kun:'あし',     on:'ソク', en:'foot / leg',
        strokes:7,
        examples:[
          {word:'足跡',reading:'ashiato',meaning:'footprint'},
          {word:'足りる',reading:'tariru',meaning:'to be enough'},
          {word:'遠足',reading:'ENSOKU',meaning:'field trip'},
        ] },
      { id:'face',  kanji:'顔', kun:'かお',     on:'ガン', en:'face',
        strokes:18,
        examples:[
          {word:'顔色',reading:'kaoiro',meaning:'complexion'},
          {word:'笑顔',reading:'egao',meaning:'smile'},
          {word:'顔面',reading:'GANMEN',meaning:'face surface'},
        ] },
      { id:'head',  kanji:'頭', kun:'あたま',   on:'トウ', en:'head',
        strokes:16,
        examples:[
          {word:'頭痛',reading:'ZUTSŪ',meaning:'headache'},
          {word:'先頭',reading:'SENTŌ',meaning:'lead / front'},
          {word:'頭金',reading:'atamakin',meaning:'down payment'},
        ] },
      { id:'hair',  kanji:'髪', kun:'かみ',     on:'ハツ', en:'hair',
        strokes:14,
        examples:[
          {word:'髪型',reading:'kamigata',meaning:'hairstyle'},
          {word:'髪の毛',reading:'kaminoke',meaning:'strand of hair'},
          {word:'金髪',reading:'KINPATSU',meaning:'blond hair'},
        ] },
      { id:'tooth', kanji:'歯', kun:'は',       on:'シ',   en:'tooth',
        strokes:12,
        examples:[
          {word:'歯医者',reading:'haisha',meaning:'dentist'},
          {word:'歯磨き',reading:'hamigaki',meaning:'toothbrushing'},
          {word:'虫歯',reading:'mushiba',meaning:'cavity'},
        ] },
      { id:'heart', kanji:'心', kun:'こころ',   on:'シン', en:'heart / mind',
        strokes:4,
        examples:[
          {word:'安心',reading:'ANSHIN',meaning:'peace of mind'},
          {word:'心配',reading:'SHINPAI',meaning:'worry'},
          {word:'心臓',reading:'SHINZŌ',meaning:'heart (organ)'},
        ] },
      { id:'nose',  kanji:'鼻', kun:'はな',     on:'ビ',   en:'nose',
        strokes:14,
        examples:[
          {word:'鼻水',reading:'hanamizu',meaning:'runny nose'},
          {word:'鼻歌',reading:'hanauta',meaning:'humming'},
          {word:'鼻血',reading:'hanaji',meaning:'nosebleed'},
        ] },
      { id:'arm',   kanji:'腕', kun:'うで',     on:'ワン', en:'arm',
        strokes:12,
        examples:[
          {word:'腕時計',reading:'udedokei',meaning:'wristwatch'},
          {word:'腕前',reading:'udemae',meaning:'skill'},
          {word:'腕立て伏せ',reading:'udetatefuse',meaning:'push-up'},
        ] },
    ],
  },
  {
    id: 'directions',
    titleJa: 'ほうこう',
    titleEn: 'Directions',
    glyph: '方',
    cards: [
      { id:'up',    kanji:'上', kun:'うえ',   on:'ジョウ', en:'up / above',
        strokes:3,
        examples:[
          {word:'上手',reading:'jōzu',meaning:'skilled'},
          {word:'以上',reading:'IJŌ',meaning:'or more'},
          {word:'上着',reading:'uwagi',meaning:'jacket'},
        ] },
      { id:'down',  kanji:'下', kun:'した',   on:'カ',     en:'down / below',
        strokes:3,
        examples:[
          {word:'下手',reading:'heta',meaning:'unskilled'},
          {word:'地下',reading:'CHIKA',meaning:'underground'},
          {word:'下着',reading:'shitagi',meaning:'underwear'},
        ] },
      { id:'left',  kanji:'左', kun:'ひだり', on:'サ',     en:'left',
        strokes:5,
        examples:[
          {word:'左手',reading:'hidarite',meaning:'left hand'},
          {word:'左右',reading:'SAYŪ',meaning:'left and right'},
          {word:'左折',reading:'SASETSU',meaning:'left turn'},
        ] },
      { id:'right', kanji:'右', kun:'みぎ',   on:'ウ',     en:'right',
        strokes:5,
        examples:[
          {word:'右手',reading:'migite',meaning:'right hand'},
          {word:'右折',reading:'USETSU',meaning:'right turn'},
          {word:'左右',reading:'SAYŪ',meaning:'left and right'},
        ] },
      { id:'middle',kanji:'中', kun:'なか',   on:'チュウ', en:'middle / inside',
        strokes:4,
        examples:[
          {word:'中学',reading:'CHŪGAKU',meaning:'middle school'},
          {word:'中心',reading:'CHŪSHIN',meaning:'center'},
          {word:'世界中',reading:'SEKAIJŪ',meaning:'worldwide'},
        ] },
    ],
  },
  {
    id: 'rooms',
    titleJa: 'へや',
    titleEn: 'Rooms',
    glyph: '室',
    // Order: boundaries (door, gate, window) → opening verbs →
    // surfaces (floor, ceiling) → contents (shelf, bookshelf).
    cards: [
      { id:'door',      kanji:'戸',   kun:'と',     on:'コ',         en:'door',
        strokes:4,
        examples:[
          {word:'戸棚',reading:'todana',meaning:'cupboard'},
          {word:'木戸',reading:'kido',meaning:'wooden gate'},
          {word:'戸口',reading:'toguchi',meaning:'doorway'},
        ] },
      { id:'gate',      kanji:'門',   kun:'かど',   on:'モン',       en:'gate',
        strokes:8,
        examples:[
          {word:'門前',reading:'MONZEN',meaning:'before the gate'},
          {word:'専門',reading:'SENMON',meaning:'specialty'},
          {word:'正門',reading:'SEIMON',meaning:'main gate'},
        ] },
      { id:'sidedoor',  kanji:'閤',   kun:'こう',   on:'コウ',       en:'side door',
        strokes:14 },
      { id:'window',    kanji:'窓',   kun:'まど',   on:'ソウ',       en:'window',
        strokes:11,
        examples:[
          {word:'窓口',reading:'madoguchi',meaning:'counter / window'},
          {word:'窓際',reading:'madogiwa',meaning:'by the window'},
          {word:'窓辺',reading:'madobe',meaning:'windowsill'},
        ] },
      { id:'open',      kanji:'開',   kun:'ひら',   on:'カイ',       en:'open',
        strokes:12,
        examples:[
          {word:'開始',reading:'KAISHI',meaning:'start'},
          {word:'公開',reading:'KŌKAI',meaning:'public release'},
          {word:'開く',reading:'hiraku',meaning:'to open'},
        ] },
      { id:'exit',      kanji:'出',   kun:'で',     on:'シュツ',     en:'go out / exit',
        strokes:5,
        examples:[
          {word:'出口',reading:'deguchi',meaning:'exit'},
          {word:'出発',reading:'SHUPPATSU',meaning:'departure'},
          {word:'出来る',reading:'dekiru',meaning:'can do'},
        ] },
      { id:'floor',     kanji:'床',   kun:'ゆか',   on:'ショウ',     en:'floor',
        strokes:7,
        examples:[
          {word:'床の間',reading:'tokonoma',meaning:'alcove'},
          {word:'起床',reading:'KISHŌ',meaning:'getting up'},
          {word:'床屋',reading:'tokoya',meaning:'barber'},
        ] },
      { id:'ceiling',   kanji:'天井', kun:'てんじょう', on:'テンジョウ', en:'ceiling',
        strokes:8 },
      { id:'shelf',     kanji:'棚',   kun:'たな',   on:'',           en:'shelf',
        strokes:12,
        examples:[
          {word:'本棚',reading:'hondana',meaning:'bookshelf'},
          {word:'棚上げ',reading:'tanaage',meaning:'shelving'},
          {word:'戸棚',reading:'todana',meaning:'cupboard'},
        ] },
      { id:'bookshelf', kanji:'本棚', kun:'ほんだな', on:'ホンダナ',   en:'bookshelf',
        strokes:17 },
    ],
  },
  // ── Grade 1 additions ────────────────────────────────────────────
  {
    id: 'numbers',
    titleJa: 'すうじ',
    titleEn: 'Numbers',
    glyph: '数',
    cards: [
      { id:'one',      kanji:'一', kun:'ひと',     on:'イチ',   en:'one', strokes:1, examples:[{word:'一月',reading:'ICHIGATSU',meaning:'January'},{word:'一人',reading:'hitori',meaning:'one person'},{word:'一番',reading:'ICHIBAN',meaning:'number one'}] },
      { id:'two',      kanji:'二', kun:'ふた',     on:'ニ',     en:'two', strokes:2, examples:[{word:'二月',reading:'NIGATSU',meaning:'February'},{word:'二人',reading:'futari',meaning:'two people'},{word:'二階',reading:'NIKAI',meaning:'second floor'}] },
      { id:'three',    kanji:'三', kun:'み',       on:'サン',   en:'three', strokes:3, examples:[{word:'三月',reading:'SANGATSU',meaning:'March'},{word:'三角',reading:'SANKAKU',meaning:'triangle'},{word:'三つ',reading:'mittsu',meaning:'three things'}] },
      { id:'four',     kanji:'四', kun:'よ',       on:'シ',     en:'four', strokes:5, examples:[{word:'四月',reading:'SHIGATSU',meaning:'April'},{word:'四季',reading:'SHIKI',meaning:'four seasons'},{word:'四角',reading:'SHIKAKU',meaning:'square'}] },
      { id:'five',     kanji:'五', kun:'いつ',     on:'ゴ',     en:'five', strokes:4, examples:[{word:'五月',reading:'GOGATSU',meaning:'May'},{word:'五感',reading:'GOKAN',meaning:'five senses'},{word:'五つ',reading:'itsutsu',meaning:'five things'}] },
      { id:'six',      kanji:'六', kun:'む',       on:'ロク',   en:'six', strokes:4, examples:[{word:'六月',reading:'ROKUGATSU',meaning:'June'},{word:'六つ',reading:'muttsu',meaning:'six things'},{word:'六本木',reading:'ROPPONGI',meaning:'Roppongi'}] },
      { id:'seven',    kanji:'七', kun:'なな',     on:'シチ',   en:'seven', strokes:2, examples:[{word:'七月',reading:'SHICHIGATSU',meaning:'July'},{word:'七夕',reading:'tanabata',meaning:'Star Festival'},{word:'七つ',reading:'nanatsu',meaning:'seven things'}] },
      { id:'eight',    kanji:'八', kun:'や',       on:'ハチ',   en:'eight', strokes:2, examples:[{word:'八月',reading:'HACHIGATSU',meaning:'August'},{word:'八百屋',reading:'yaoya',meaning:'greengrocer'},{word:'八つ',reading:'yattsu',meaning:'eight things'}] },
      { id:'nine',     kanji:'九', kun:'ここの',   on:'キュウ', en:'nine', strokes:2, examples:[{word:'九月',reading:'KUGATSU',meaning:'September'},{word:'九州',reading:'KYŪSHŪ',meaning:'Kyushu'},{word:'九つ',reading:'kokonotsu',meaning:'nine things'}] },
      { id:'ten',      kanji:'十', kun:'とお',     on:'ジュウ', en:'ten', strokes:2, examples:[{word:'十月',reading:'JŪGATSU',meaning:'October'},{word:'十分',reading:'JŪBUN',meaning:'enough'},{word:'十字路',reading:'JŪJIRO',meaning:'crossroads'}] },
      { id:'hundred',  kanji:'百', kun:'もも',     on:'ヒャク', en:'hundred', strokes:6, examples:[{word:'百円',reading:'HYAKUEN',meaning:'100 yen'},{word:'百科',reading:'HYAKKA',meaning:'encyclopedia'},{word:'三百',reading:'SANBYAKU',meaning:'three hundred'}] },
      { id:'thousand', kanji:'千', kun:'ち',       on:'セン',   en:'thousand', strokes:3, examples:[{word:'千円',reading:'SEN\'EN',meaning:'1000 yen'},{word:'千葉',reading:'CHIBA',meaning:'Chiba'},{word:'千年',reading:'SENNEN',meaning:'millennium'}] },
    ],
  },
  {
    id: 'colors',
    titleJa: 'いろ',
    titleEn: 'Colors',
    glyph: '色',
    cards: [
      { id:'white',    kanji:'白', kun:'しろ',     on:'ハク',   en:'white', strokes:5, examples:[{word:'白紙',reading:'HAKUSHI',meaning:'blank paper'},{word:'白黒',reading:'SHIROKURO',meaning:'black and white'},{word:'白鳥',reading:'HAKUCHŌ',meaning:'swan'}] },
      { id:'red',      kanji:'赤', kun:'あか',     on:'セキ',   en:'red', strokes:7, examples:[{word:'赤ちゃん',reading:'akachan',meaning:'baby'},{word:'赤道',reading:'SEKIDŌ',meaning:'equator'},{word:'赤字',reading:'AKAJI',meaning:'deficit'}] },
      { id:'blue',     kanji:'青', kun:'あお',     on:'セイ',   en:'blue / green', strokes:8, examples:[{word:'青空',reading:'aozora',meaning:'blue sky'},{word:'青年',reading:'SEINEN',meaning:'youth'},{word:'青春',reading:'SEISHUN',meaning:'springtime of life'}] },
    ],
  },
  {
    id: 'time',
    titleJa: 'とき',
    titleEn: 'Time',
    glyph: '時',
    cards: [
      { id:'year',     kanji:'年', kun:'とし',     on:'ネン',   en:'year', strokes:6, examples:[{word:'去年',reading:'KYONEN',meaning:'last year'},{word:'今年',reading:'kotoshi',meaning:'this year'},{word:'年齢',reading:'NENREI',meaning:'age'}] },
      { id:'early',    kanji:'早', kun:'はや',     on:'ソウ',   en:'early / fast', strokes:6, examples:[{word:'早朝',reading:'SŌCHŌ',meaning:'early morning'},{word:'早い',reading:'hayai',meaning:'early'},{word:'早起き',reading:'hayaoki',meaning:'early rising'}] },
      { id:'evening',  kanji:'夕', kun:'ゆう',     on:'セキ',   en:'evening', strokes:3, examples:[{word:'夕方',reading:'yūgata',meaning:'evening'},{word:'夕食',reading:'YŪSHOKU',meaning:'dinner'},{word:'夕日',reading:'yūhi',meaning:'sunset'}] },
      { id:'ahead',    kanji:'先', kun:'さき',     on:'セン',   en:'ahead / previous / tip', strokes:6, examples:[{word:'先生',reading:'SENSEI',meaning:'teacher'},{word:'先月',reading:'SENGETSU',meaning:'last month'},{word:'先端',reading:'SENTAN',meaning:'cutting edge'}] },
    ],
  },
  {
    id: 'school',
    titleJa: 'がっこう',
    titleEn: 'School',
    glyph: '学',
    cards: [
      { id:'learn',    kanji:'学', kun:'まな',     on:'ガク',   en:'learn / study',
        seeAlso:['子'], strokes:8, examples:[{word:'学校',reading:'GAKKŌ',meaning:'school'},{word:'学生',reading:'GAKUSEI',meaning:'student'},{word:'学ぶ',reading:'manabu',meaning:'to learn'}] },
      { id:'school',   kanji:'校', kun:'',         on:'コウ',   en:'school', strokes:10, examples:[{word:'学校',reading:'GAKKŌ',meaning:'school'},{word:'校長',reading:'KŌCHŌ',meaning:'principal'},{word:'高校',reading:'KŌKŌ',meaning:'high school'}] },
      { id:'writing',  kanji:'文', kun:'ふみ',     on:'ブン',   en:'writing / text / culture', strokes:4, examples:[{word:'文化',reading:'BUNKA',meaning:'culture'},{word:'文学',reading:'BUNGAKU',meaning:'literature'},{word:'文字',reading:'MOJI',meaning:'character'}] },
      { id:'name',     kanji:'名', kun:'な',       on:'メイ',   en:'name / fame', strokes:6, examples:[{word:'名前',reading:'namae',meaning:'name'},{word:'名人',reading:'MEIJIN',meaning:'master'},{word:'有名',reading:'YŪMEI',meaning:'famous'}] },
      { id:'correct',  kanji:'正', kun:'ただ',     on:'セイ',   en:'correct / proper / just',
        seeAlso:['足'], strokes:5, examples:[{word:'正月',reading:'SHŌGATSU',meaning:'New Year'},{word:'正直',reading:'SHŌJIKI',meaning:'honest'},{word:'正しい',reading:'tadashii',meaning:'correct'}] },
    ],
  },
];

// Flat list for any code that still expects FLASHCARDS as a single array.
window.FLASHCARDS = window.FLASHCARD_CLASSES.flatMap(c => c.cards);

// ── DICTIONARY ─────────────────────────────────────────────────────────
// Mixed kanji + vocabulary index. Each entry has kind ('kanji' | 'word')
// so the dictionary can filter by it.
window.DICTIONARY = [
  // single kanji
  { kind:'kanji', kanji:'風', kana:'かぜ',     en:'wind',            level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'水', kana:'みず',     en:'water',           level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'火', kana:'ひ',       en:'fire',            level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'山', kana:'やま',     en:'mountain',        level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'川', kana:'かわ',     en:'river',           level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'人', kana:'ひと',     en:'person',          level:'N5', tags:[] },
  { kind:'kanji', kanji:'入', kana:'はい.る',  en:'enter / put in',  level:'N5', tags:[] },
  { kind:'kanji', kanji:'出', kana:'で.る',    en:'go out / exit',   level:'N5', tags:[] },
  { kind:'kanji', kanji:'戸', kana:'と',       en:'door',            level:'N3', tags:[] },
  { kind:'kanji', kanji:'門', kana:'もん',     en:'gate',            level:'N3', tags:[] },
  { kind:'kanji', kanji:'閤', kana:'こう',     en:'side door',       level:'N1', tags:[] },
  { kind:'kanji', kanji:'開', kana:'ひら.く',  en:'open',            level:'N4', tags:[] },
  { kind:'kanji', kanji:'床', kana:'ゆか',     en:'floor',           level:'N3', tags:['home'] },
  { kind:'kanji', kanji:'棚', kana:'たな',     en:'shelf',           level:'N2', tags:['home'] },
  { kind:'word',  kanji:'天井', kana:'てんじょう', en:'ceiling',         level:'N3', tags:['home'] },
  { kind:'kanji', kanji:'父', kana:'ちち',     en:'father',          level:'N5', tags:[] },
  { kind:'kanji', kanji:'母', kana:'はは',     en:'mother',          level:'N5', tags:[] },
  { kind:'kanji', kanji:'兄', kana:'あに',     en:'older brother',   level:'N5', tags:[] },
  { kind:'kanji', kanji:'姉', kana:'あね',     en:'older sister',    level:'N5', tags:[] },
  { kind:'kanji', kanji:'弟', kana:'おとうと', en:'younger brother', level:'N4', tags:[] },
  { kind:'kanji', kanji:'妹', kana:'いもうと', en:'younger sister',  level:'N4', tags:[] },
  { kind:'word',  kanji:'姉妹', kana:'しまい',    en:'sisters',            level:'N4', tags:[] },
  { kind:'word',  kanji:'兄弟', kana:'きょうだい', en:'brothers / siblings', level:'N4', tags:[] },
  { kind:'kanji', kanji:'子', kana:'こ',       en:'child',           level:'N5', tags:[] },
  { kind:'kanji', kanji:'女', kana:'おんな',   en:'woman',           level:'N5', tags:[] },
  { kind:'kanji', kanji:'好', kana:'す.き',    en:'like / fond',     level:'N5', tags:[] },
  { kind:'kanji', kanji:'字', kana:'じ',       en:'character / letter', level:'N4', tags:[] },
  { kind:'kanji', kanji:'男', kana:'おとこ',   en:'man',             level:'N5', tags:[] },
  { kind:'kanji', kanji:'毎', kana:'まい',     en:'every',           level:'N5', tags:['time'] },
  { kind:'kanji', kanji:'友', kana:'とも',     en:'friend',          level:'N4', tags:[] },
  { kind:'kanji', kanji:'反', kana:'はん',     en:'anti- / opposite', level:'N3', tags:[] },
  { kind:'kanji', kanji:'氷', kana:'こおり',   en:'ice',             level:'N3', tags:['nature'] },
  { kind:'kanji', kanji:'雪', kana:'ゆき',     en:'snow',            level:'N4', tags:['nature'] },
  { kind:'kanji', kanji:'空', kana:'そら',     en:'sky',             level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'雲', kana:'くも',     en:'cloud',           level:'N4', tags:['nature'] },
  { kind:'kanji', kanji:'星', kana:'ほし',     en:'star',            level:'N4', tags:['nature'] },
  { kind:'kanji', kanji:'葉', kana:'は',       en:'leaf',            level:'N3', tags:['nature'] },
  { kind:'kanji', kanji:'草', kana:'くさ',     en:'grass',           level:'N3', tags:['nature'] },
  { kind:'kanji', kanji:'未', kana:'まだ',     en:'not yet / unripe', level:'N3', tags:[] },
  { kind:'kanji', kanji:'木', kana:'き',       en:'tree',            level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'本', kana:'ほん',     en:'book / origin / root', level:'N5', tags:['home'] },
  { kind:'kanji', kanji:'林', kana:'はやし',   en:'woods',           level:'N4', tags:['nature'] },
  { kind:'kanji', kanji:'森', kana:'もり',     en:'forest',          level:'N4', tags:['nature'] },
  { kind:'kanji', kanji:'厂', kana:'がけ',     en:'cliff (radical)', level:'—', tags:['nature'] },
  { kind:'kanji', kanji:'石', kana:'いし',     en:'stone / rock',    level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'岩', kana:'いわ',     en:'rock / boulder',  level:'N3', tags:['nature'] },
  { kind:'kanji', kanji:'宕', kana:'ほら',     en:'cave',            level:'—', tags:['nature'] },
  { kind:'kanji', kanji:'土', kana:'つち',     en:'earth / soil / Saturday', level:'N5', tags:['nature','time'] },
  { kind:'kanji', kanji:'去', kana:'さ.る',   en:'to leave / past',  level:'N4', tags:['time'] },
  { kind:'kanji', kanji:'刀', kana:'かたな',   en:'katana / sword',   level:'N3', tags:[] },
  { kind:'kanji', kanji:'力', kana:'ちから',   en:'power / strength', level:'N4', tags:[] },
  { kind:'kanji', kanji:'弓', kana:'ゆみ',     en:'bow',              level:'N3', tags:[] },
  { kind:'kanji', kanji:'市', kana:'いち',     en:'market / city',    level:'N4', tags:[] },
  { kind:'kanji', kanji:'田', kana:'た',       en:'rice field',       level:'N4', tags:['nature'] },
  { kind:'kanji', kanji:'町', kana:'まち',     en:'town',             level:'N4', tags:[] },
  { kind:'kanji', kanji:'村', kana:'むら',     en:'village',          level:'N4', tags:[] },
  { kind:'kanji', kanji:'王', kana:'おう',     en:'king',             level:'N4', tags:[] },
  { kind:'kanji', kanji:'生', kana:'なま',     en:'life / raw',       level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'国', kana:'くに',     en:'country',          level:'N5', tags:[] },
  { kind:'kanji', kanji:'宀', kana:'うかんむり', en:'roof / crown / cap (radical)', level:'—', tags:[] },
  { kind:'kanji', kanji:'円', kana:'えん',     en:'yen / circle',     level:'N5', tags:[] },
  { kind:'kanji', kanji:'大', kana:'おお',     en:'big / large',      level:'N5', tags:['adj'] },
  { kind:'kanji', kanji:'小', kana:'ちい',     en:'small',            level:'N5', tags:['adj'] },
  { kind:'kanji', kanji:'上', kana:'うえ',     en:'up / above',       level:'N5', tags:[] },
  { kind:'kanji', kanji:'下', kana:'した',     en:'down / below',     level:'N5', tags:[] },
  { kind:'kanji', kanji:'日', kana:'ひ',       en:'sun / day',       level:'N5', tags:['time'] },
  { kind:'kanji', kanji:'月', kana:'つき',     en:'moon / month',    level:'N5', tags:['time'] },
  { kind:'kanji', kanji:'目', kana:'め',       en:'eye',             level:'N5', tags:['body'] },
  { kind:'kanji', kanji:'体', kana:'からだ',   en:'body',            level:'N5', tags:['body'] },
  { kind:'kanji', kanji:'手', kana:'て',       en:'hand',            level:'N5', tags:['body'] },
  { kind:'kanji', kanji:'見', kana:'み.る',    en:'look / see',      level:'N5', tags:[] },
  { kind:'kanji', kanji:'自', kana:'じ',       en:'self / oneself',  level:'N4', tags:[] },
  { kind:'kanji', kanji:'口', kana:'くち',     en:'mouth / opening / entrance', level:'N5', tags:['body'] },
  { kind:'kanji', kanji:'耳', kana:'みみ',     en:'ear',             level:'N5', tags:['body'] },
  { kind:'kanji', kanji:'鼻', kana:'はな',     en:'nose',            level:'N3', tags:['body'] },
  { kind:'kanji', kanji:'足', kana:'あし',     en:'foot / leg',      level:'N5', tags:['body'] },
  { kind:'kanji', kanji:'顔', kana:'かお',     en:'face',            level:'N4', tags:['body'] },
  { kind:'kanji', kanji:'頭', kana:'あたま',   en:'head',            level:'N4', tags:['body'] },
  { kind:'kanji', kanji:'髪', kana:'かみ',     en:'hair',            level:'N4', tags:['body'] },
  { kind:'kanji', kanji:'歯', kana:'は',       en:'tooth',           level:'N4', tags:['body'] },
  { kind:'kanji', kanji:'心', kana:'こころ',   en:'heart / mind',    level:'N4', tags:['body'] },
  { kind:'kanji', kanji:'腕', kana:'うで',     en:'arm',             level:'N3', tags:['body'] },
  { kind:'kanji', kanji:'首', kana:'くび',     en:'neck',            level:'N3', tags:['body'] },
  { kind:'kanji', kanji:'花', kana:'はな',     en:'flower',          level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'雨', kana:'あめ',     en:'rain',            level:'N5', tags:['nature'] },
  { kind:'kanji', kanji:'春', kana:'はる',     en:'spring',          level:'N5', tags:['time','nature'] },
  { kind:'kanji', kanji:'夏', kana:'なつ',     en:'summer',          level:'N5', tags:['time','nature'] },
  { kind:'kanji', kanji:'秋', kana:'あき',     en:'autumn',          level:'N5', tags:['time','nature'] },
  { kind:'kanji', kanji:'冬', kana:'ふゆ',     en:'winter',          level:'N5', tags:['time','nature'] },
  { kind:'kanji', kanji:'虫', kana:'むし',     en:'insect',          level:'N4', tags:['animal','nature'] },
  { kind:'kanji', kanji:'鏡', kana:'かがみ',   en:'mirror',          level:'N4', tags:['home'] },
  { kind:'kanji', kanji:'窓', kana:'まど',     en:'window',          level:'N4', tags:['home'] },
  { kind:'kanji', kanji:'蛇', kana:'へび',     en:'snake',           level:'N2', tags:['animal'] },
  { kind:'kanji', kanji:'鍵', kana:'かぎ',     en:'key',              level:'N2', tags:['home'] },
  { kind:'kanji', kanji:'浴', kana:'ヨク',     en:'bathe',           level:'N3', tags:['home'] },
  { kind:'kanji', kanji:'寝', kana:'ね.る',    en:'sleep',           level:'N3', tags:['home'] },
  { kind:'kanji', kanji:'冷', kana:'つめ.たい', en:'cold (to touch)',level:'N3', tags:['adj'] },

  // words
  { kind:'word', kanji:'浴室',       kana:'よくしつ',    en:'bathroom',       level:'N4', tags:['home','bathroom'] },
  { kind:'word', kanji:'洗面台',     kana:'せんめんだい', en:'washbasin',     level:'N3', tags:['home','bathroom'] },
  { kind:'word', kanji:'蛇口',       kana:'じゃぐち',    en:'faucet',         level:'N2', tags:['home','bathroom'] },
  { kind:'word', kanji:'シャワー',   kana:'しゃわー',    en:'shower',         level:'N5', tags:['home','bathroom'] },
  { kind:'word', kanji:'浴槽',       kana:'よくそう',    en:'bathtub',        level:'N2', tags:['home','bathroom'] },
  { kind:'word', kanji:'トイレ',     kana:'といれ',      en:'toilet',         level:'N5', tags:['home','bathroom'] },
  { kind:'word', kanji:'タオル',     kana:'たおる',      en:'towel',          level:'N5', tags:['home'] },
  { kind:'word', kanji:'歯ブラシ',   kana:'はぶらし',    en:'toothbrush',     level:'N4', tags:['home','bathroom'] },
  { kind:'word', kanji:'冷蔵庫',     kana:'れいぞうこ',  en:'refrigerator',   level:'N4', tags:['home','kitchen'] },
  { kind:'word', kanji:'電子レンジ', kana:'でんしれんじ',en:'microwave',      level:'N3', tags:['home','kitchen'] },
  { kind:'word', kanji:'包丁',       kana:'ほうちょう',  en:'kitchen knife',  level:'N3', tags:['home','kitchen'] },
  { kind:'word', kanji:'お皿',       kana:'おさら',      en:'plate',          level:'N5', tags:['home','kitchen'] },
  { kind:'word', kanji:'箸',         kana:'はし',        en:'chopsticks',     level:'N5', tags:['home','kitchen'] },
  { kind:'word', kanji:'ソファ',     kana:'そふぁ',      en:'sofa',           level:'N5', tags:['home','livingroom'] },
  { kind:'word', kanji:'テレビ',     kana:'てれび',      en:'television',     level:'N5', tags:['home','livingroom'] },
  { kind:'word', kanji:'本棚',       kana:'ほんだな',    en:'bookshelf',      level:'N4', tags:['home','livingroom'] },
  { kind:'word', kanji:'カーテン',   kana:'かーてん',    en:'curtain',        level:'N5', tags:['home'] },
  { kind:'word', kanji:'ベッド',     kana:'べっど',      en:'bed',            level:'N5', tags:['home','bedroom'] },
  { kind:'word', kanji:'布団',       kana:'ふとん',      en:'futon / duvet',  level:'N4', tags:['home','bedroom'] },
  { kind:'word', kanji:'枕',         kana:'まくら',      en:'pillow',         level:'N3', tags:['home','bedroom'] },
  { kind:'word', kanji:'目覚まし時計',kana:'めざましどけい',en:'alarm clock',  level:'N3', tags:['home','bedroom'] },
  { kind:'word', kanji:'玄関',       kana:'げんかん',    en:'entryway',       level:'N4', tags:['home','entrance'] },
  { kind:'word', kanji:'靴',         kana:'くつ',        en:'shoes',          level:'N5', tags:['home','entrance'] },
  { kind:'word', kanji:'傘',         kana:'かさ',        en:'umbrella',       level:'N4', tags:['home','entrance'] },
  { kind:'word', kanji:'鍵',         kana:'かぎ',        en:'key',            level:'N3', tags:['home','entrance'] },
];

// ── LEVELS ─────────────────────────────────────────────────────────────
window.JLPT_LEVELS = ['N5', 'N4', 'N3', 'N2', 'N1'];

// ── KANJI READINGS ─────────────────────────────────────────────────────
// Default reading per kanji, used as furigana in the popover. Kanji
// readings are context-dependent (浴 reads よく in 浴室 but あ in 浴びる) — this
// map captures the *most common* reading for our seed vocabulary. Words
// that need a different reading can override later via per-word data.
window.KANJI_READINGS = {
  // bathroom
  '浴':'よく', '室':'しつ', '鏡':'かがみ', '洗':'せん', '面':'めん',
  '台':'だい', '所':'しょ', '蛇':'じゃ', '口':'くち', '槽':'そう',
  '窓':'まど', '紙':'がみ', '便':'びん', '器':'き',
  '石':'いし', '鹸':'けん', '歯':'は', '磨':'みが', '粉':'こ',
  '液':'えき', '体':'たい',

  // kitchen
  '冷':'れい', '蔵':'ぞう', '庫':'こ',
  '電':'でん', '子':'こ',
  '包':'ほう', '丁':'ちょう',
  '皿':'さら', '箸':'はし', '鍋':'なべ',
  '板':'いた', '野':'や', '菜':'さい',
  '料':'りょう', '理':'り',
  '湯':'ゆ', '水':'みず', '火':'ひ',
  '麺':'めん',

  // living room
  '本':'ほん', '棚':'だな',
  '時':'と', '計':'けい',
  '植':'う', '木':'き', '鉢':'ばち',
  '絨':'じゅう', '毯':'たん',

  // bedroom
  '枕':'まくら', '布':'ふ', '団':'とん',
  '目':'め', '覚':'ざ', '引':'ひ', '出':'で',

  // entrance
  '玄':'げん', '関':'かん',
  '靴':'くつ', '傘':'かさ', '鍵':'かぎ',
  '郵':'ゆう', '受':'う',
  '家':'いえ', '入':'はい',

  // common verb / sentence kanji
  '食':'た', '前':'まえ', '手':'て', '毎':'まい', '日':'にち',
  '寒':'さむ', '人':'ひと', '夜':'よる', '朝':'あさ',
  '晩':'ばん', '眠':'ねむ',
  '顔':'かお', '拭':'ふ', '呂':'ろ',
  '開':'あ', '一':'いち',
  '飯':'はん', '作':'つく', '何':'なに',
  '呼':'よ', '脱':'ぬ', '降':'ふ',
  '持':'も', '切':'き', '座':'すわ', '履':'は',
  '空':'そら', '気':'き', '新':'しん', '鮮':'せん',
  '湿':'しめ', '残':'のこ', '行':'い', '来':'く',
  '中':'なか', '友':'とも', '達':'たち',
  '部':'へ', '屋':'や',
  '見':'み', '読':'よ', '休':'やす', '飲':'の', '聞':'き',
  '寝':'ね', '起':'お', '熱':'ねつ',
  '小':'ちい', '少':'すこ', '十':'じゅう', '七':'なな',
  '茶':'ちゃ', '若':'わか',
  '夕':'ゆう', '昼':'ひる',
  '母':'はは', '父':'ちち', '私':'わたし',
  '危':'あぶ', '沸':'わ',
  '整':'ととの', '髪':'かみ', '乾':'かわ',
  '風':'かぜ', '邪':'じゃ', '景':'けい',
  '緒':'しょ', '始':'はじ',
  '閉':'し', '忘':'わす',
  '生':'い',
  '山':'やま', '川':'かわ', '月':'つき', '雨':'あめ', '雪':'ゆき',
  '春':'はる', '夏':'なつ', '秋':'あき', '冬':'ふゆ', '虫':'むし',
  '林':'はやし', '森':'もり',
  '土':'つち', '去':'さ', '王':'おう', '国':'くに',
  '刀':'かたな', '力':'ちから', '弓':'ゆみ', '市':'いち', '田':'た', '町':'まち', '村':'むら',
  '円':'えん',
  '上':'うえ', '下':'した',
  '大':'おお',
  '戸':'と', '門':'もん',
  '床':'ゆか', '天':'てん', '井':'じょう',
  '閤':'こう',
  '厂':'がけ',
  '岩':'いわ',
  '宀':'うかんむり', '宕':'ほら',
  '字':'じ', '書':'か',
  '鼻':'はな', '耳':'みみ',
  '父':'ちち', '母':'はは', '女':'おんな', '男':'おとこ', '好':'す',
  '反':'はん', '氷':'こおり',
  '葉':'は', '星':'ほし', '雲':'くも',
  '足':'あし', '頭':'あたま', '心':'こころ', '腕':'うで', '首':'くび',
  '兄':'あに', '姉':'あね', '弟':'おとうと', '妹':'いもうと',
  '自':'じ', '未':'まだ',
  '光':'ひかり', '音':'おと', '声':'こえ', '花':'はな', '草':'くさ',
  '海':'うみ', '河':'かわ', '池':'いけ', '流':'なが', '泳':'およ',
  '汽':'き', '注':'そそ', '沢':'さわ', '漢':'かん',
  '強':'つよ', '弱':'よわ',

  // Grade 1 additions
  '一':'いち', '二':'に', '三':'さん', '四':'よん', '五':'ご',
  '六':'ろく', '七':'なな', '八':'はち', '九':'きゅう', '十':'じゅう',
  '百':'ひゃく', '千':'せん',
  '白':'しろ', '赤':'あか', '青':'あお',
  '金':'かね', '玉':'たま', '糸':'いと', '車':'くるま', '立':'た',
  '休':'やす', '犬':'いぬ', '貝':'かい', '気':'き', '竹':'たけ',
  '左':'ひだり', '右':'みぎ',
  '年':'とし', '早':'はや', '夕':'ゆう', '先':'さき',
  '学':'まな', '校':'こう', '文':'ぶん', '名':'な', '正':'ただ',
};

// ── KANJI MEANINGS ─────────────────────────────────────────────────────
// Used to render the per-character breakdown of multi-kanji words inside
// the vocab popover (e.g. 浴室 → 浴 = bathe, 室 = room). Keep entries short
// and concrete — one or two words, lowercase. Extendable: add as you grow.
window.KANJI_MEANINGS = {
  // bathroom
  '浴':'bathe', '室':'room', '鏡':'mirror', '洗':'wash', '面':'face',
  '台':'stand', '所':'place', '蛇':'snake', '口':'mouth / opening', '槽':'tank',
  '窓':'window', '紙':'paper', '便':'convenience', '器':'container',
  '石':'stone', '鹸':'lye', '歯':'tooth', '磨':'polish', '粉':'powder',
  '液':'liquid', '体':'body',

  // kitchen
  '冷':'cold', '蔵':'storage', '庫':'warehouse',
  '電':'electric', '子':'child',
  '包':'wrap', '丁':'chop',
  '皿':'plate', '箸':'chopsticks', '鍋':'pot',
  '板':'board', '野':'field', '菜':'vegetable',
  '料':'fee', '理':'reason',
  '湯':'hot water', '水':'water', '火':'fire',
  '麺':'noodle',

  // living room
  '本':'book', '棚':'shelf',
  '時':'time', '計':'count',
  '植':'plant', '木':'tree', '鉢':'bowl',
  '絨':'rug', '毯':'blanket',

  // bedroom
  '枕':'pillow', '布':'cloth', '団':'group',
  '目':'eye', '覚':'awake', '引':'pull', '出':'exit',

  // entrance
  '玄':'mystery', '関':'barrier',
  '靴':'shoe', '傘':'umbrella', '鍵':'key',
  '郵':'mail', '受':'receive',
  '家':'home', '入':'enter',

  // common verbs / sentence kanji
  '食':'eat', '前':'before', '手':'hand', '毎':'every', '日':'day',
  '寒':'cold', '人':'person', '夜':'night', '朝':'morning',
  '晩':'evening', '眠':'sleep',
  '顔':'face', '拭':'wipe', '呂':'bath',
  '開':'open', '一':'one',
  '飯':'meal', '作':'make', '何':'what',
  '呼':'call', '脱':'take off', '降':'fall',
  '持':'hold', '切':'cut', '座':'sit', '履':'put on',
  '空':'sky', '気':'air', '新':'new', '鮮':'fresh',
  '湿':'damp', '残':'remain', '行':'go', '来':'come',
  '中':'middle', '友':'friend', '達':'arrive',
  '部':'section', '屋':'shop',
  '見':'see', '読':'read', '休':'rest', '飲':'drink', '聞':'hear',
  '寝':'sleep', '起':'rise', '熱':'heat',
  '小':'small', '少':'few', '十':'ten', '七':'seven',
  '茶':'tea', '若':'young',
  '夕':'evening', '昼':'noon',
  '母':'mother', '父':'father', '私':'I',
  '危':'danger', '沸':'boil',
  '整':'arrange', '髪':'hair',
  '乾':'dry',
  '風':'wind', '邪':'evil', '景':'view',
  '緒':'cord', '始':'begin',
  '閉':'close', '忘':'forget',
  '生':'life',
  '山':'mountain', '川':'river', '月':'moon', '雨':'rain', '雪':'snow',
  '春':'spring', '夏':'summer', '秋':'autumn', '冬':'winter', '虫':'insect',
  '林':'woods', '森':'forest',
  '土':'earth', '去':'leave', '王':'king', '国':'country',
  '刀':'katana', '力':'power', '弓':'bow', '市':'city', '田':'field', '町':'town', '村':'village',
  '円':'yen',
  '上':'up', '下':'down',
  '大':'big',
  '戸':'door', '門':'gate',
  '床':'floor', '天':'heaven', '井':'well',
  '閤':'side door',
  '厂':'cliff',
  '岩':'rock',
  '宀':'roof / crown / cap', '宕':'cave',
  '字':'character', '書':'write / book',
  '鼻':'nose', '耳':'ear',
  '女':'woman', '男':'man', '好':'like',
  '反':'opposite', '氷':'ice',
  '葉':'leaf', '星':'star', '雲':'cloud',
  '足':'foot', '頭':'head', '心':'heart', '腕':'arm', '首':'neck',
  '兄':'older brother', '姉':'older sister', '弟':'younger brother', '妹':'younger sister',
  '自':'self', '未':'not yet',
  '光':'light', '音':'sound', '声':'voice', '花':'flower', '草':'grass',
  '海':'sea', '河':'stream', '池':'pond', '流':'flow', '泳':'swim',
  '汽':'steam', '注':'pour', '沢':'marsh', '漢':'Chinese',
  '強':'strong', '弱':'weak',

  // Grade 1 additions
  '一':'one', '二':'two', '三':'three', '四':'four', '五':'five',
  '六':'six', '七':'seven', '八':'eight', '九':'nine', '十':'ten',
  '百':'hundred', '千':'thousand',
  '白':'white', '赤':'red', '青':'blue / green',
  '金':'gold / money', '玉':'jewel', '糸':'thread', '車':'vehicle', '立':'stand',
  '休':'rest', '犬':'dog', '貝':'shell', '気':'spirit / air', '竹':'bamboo',
  '左':'left', '右':'right',
  '年':'year', '早':'early', '夕':'evening', '先':'ahead / prior',
  '学':'learn', '校':'school', '文':'writing', '名':'name', '正':'correct',
};

