#!/usr/bin/env node
/*
 * build-reader.mjs — bundles the Nihongo Reader extension into
 * reader-extension/dist/ (git-ignored; load it unpacked via chrome://extensions).
 *
 *   node scripts/build-reader.mjs          (also `npm run build:reader`)
 *
 * Same tool-time philosophy as build-vendor.mjs: the Nihongo app stays
 * no-build; only the extension is bundled, because MV3 forbids remote code
 * and the tokenizer is an npm package. Output:
 *   dist/{background,sidepanel,analysis-worker,content,offscreen,popup}.js   (esbuild, ESM)
 *   dist/manifest.json, sidepanel.html/.css, blocks.css, offscreen.html, popup.html/.css (copied)
 *   dist/dict/*.dat.gz                                                 (IPADIC, gzipped, from @patdx/kuromoji)
 *   dist/vendor-notices/                                               (licences + NOTICE)
 * Prints a size table so package growth is visible on every build.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const EXT = path.join(DIR, 'reader-extension');
const DIST = path.join(EXT, 'dist');
const KUROMOJI = path.join(DIR, 'node_modules', '@patdx', 'kuromoji');
const pkg = JSON.parse(fs.readFileSync(path.join(KUROMOJI, 'package.json'), 'utf8'));
const extensionManifest = JSON.parse(fs.readFileSync(path.join(EXT, 'manifest.json'), 'utf8'));

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(path.join(DIST, 'dict'), { recursive: true });
fs.mkdirSync(path.join(DIST, 'vendor-notices'), { recursive: true });

const result = await esbuild.build({
  entryPoints: {
    background: path.join(EXT, 'src', 'background.js'),
    sidepanel: path.join(EXT, 'src', 'sidepanel.js'),
    'analysis-worker': path.join(EXT, 'src', 'analysis-worker.js'),
    content: path.join(EXT, 'src', 'content.js'),
    offscreen: path.join(EXT, 'src', 'offscreen.js'),
    popup: path.join(EXT, 'src', 'popup.js'),
  },
  loader: { '.css': 'text' },   // content.js embeds blocks.css in its shadow root
  bundle: true,
  format: 'esm',   // content.js keeps no import/export after bundling, so it also runs as a classic content script
  platform: 'browser',
  target: ['chrome116'],
  define: { __READER_VERSION__: JSON.stringify(extensionManifest.version) },
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  outdir: DIST,
  metafile: true,
  banner: { js: `/* Nihongo Reader ${extensionManifest.version} — generated by scripts/build-reader.mjs; do not edit. Bundles ${pkg.name} v${pkg.version} (Apache-2.0). */` },
});

for (const f of ['manifest.json', 'sidepanel.html', 'sidepanel.css', 'offscreen.html', 'popup.html', 'popup.css']) fs.copyFileSync(path.join(EXT, f), path.join(DIST, f));
fs.copyFileSync(path.join(EXT, 'src', 'panel', 'blocks.css'), path.join(DIST, 'blocks.css'));
// Bundled library: the committed reader-library/ JSON plus the image bytes it references (from images/), so the
// first run works offline; the extension later upgrades from the site when a newer revision is published.
const LIB = path.join(DIR, 'reader-library');
if (fs.existsSync(path.join(LIB, 'manifest.json'))) {
  fs.mkdirSync(path.join(DIST, 'library', 'assets'), { recursive: true });
  for (const f of ['manifest.json', 'cards.json', 'glossary.json', 'lessons.json']) if (fs.existsSync(path.join(LIB, f))) fs.copyFileSync(path.join(LIB, f), path.join(DIST, 'library', f));
  const man = JSON.parse(fs.readFileSync(path.join(LIB, 'manifest.json'), 'utf8'));
  let missing = 0;
  for (const a of man.assets || []) { const src = a.sourcePath ? path.join(DIR, a.sourcePath) : null; if (src && fs.existsSync(src)) fs.copyFileSync(src, path.join(DIST, a.path.replace('assets/', 'library/assets/'))); else missing++; }
  if (missing) console.warn(`  ! ${missing} library assets not found in images/ — run npm run build:library`);
} else console.warn('  ! reader-library/manifest.json missing — run npm run build:library (extension will start without cards)');
for (const f of fs.readdirSync(path.join(KUROMOJI, 'dict'))) fs.copyFileSync(path.join(KUROMOJI, 'dict', f), path.join(DIST, 'dict', f));
fs.copyFileSync(path.join(KUROMOJI, 'LICENSE-2.0.txt'), path.join(DIST, 'vendor-notices', 'kuromoji-LICENSE-2.0.txt'));
for (const f of fs.readdirSync(path.join(EXT, 'vendor-notices'))) fs.copyFileSync(path.join(EXT, 'vendor-notices', f), path.join(DIST, 'vendor-notices', f));

// ── Size table ──────────────────────────────────────────────────────────────
const sizeOf = (p) => fs.statSync(p).size;
const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap(d => d.isDirectory() ? walk(path.join(dir, d.name)) : [path.join(dir, d.name)]);
const files = walk(DIST);
const kb = (n) => (n / 1024).toFixed(1).padStart(8) + ' KB';
let total = 0;
console.log('build-reader → reader-extension/dist/');
for (const f of files.filter(f => !f.includes(`${path.sep}dict${path.sep}`) && !f.includes(`${path.sep}library${path.sep}assets${path.sep}`))) { const s = sizeOf(f); total += s; console.log(`  ${kb(s)}  ${path.relative(DIST, f)}`); }
const libAssets = files.filter(f => f.includes(`${path.sep}library${path.sep}assets${path.sep}`)); const libBytes = libAssets.reduce((a, f) => a + sizeOf(f), 0); total += libBytes; console.log(`  ${kb(libBytes)}  library/assets/ (${libAssets.length} images, bundled library)`);
const dictBytes = files.filter(f => f.includes(`${path.sep}dict${path.sep}`)).reduce((a, f) => a + sizeOf(f), 0);
total += dictBytes;
console.log(`  ${kb(dictBytes)}  dict/ (12 files, gzipped IPADIC)`);
console.log(`  ${kb(total)}  TOTAL unpacked`);
if (Object.values(result.metafile.outputs).some(o => o.bytes === 0)) { console.error('empty output'); process.exit(1); }
