#!/usr/bin/env node
/*
 * build-vendor.mjs — regenerates the committed vendor bundles.
 *
 * The app itself stays no-build (plain <script> tags); this is a TOOL-TIME
 * step, run only when a vendored dependency is added or upgraded. The output
 * is committed so the app keeps working from a bare checkout / GitHub Pages.
 *
 *   npm run build-vendor
 *
 * Bundles:
 *   vendor/ts-fsrs.js — ts-fsrs (MIT), IIFE exposing window.TSFSRS.
 *     The FSRS spaced-repetition scheduler (the algorithm Anki adopted as
 *     its default in 2023). Used by the flashcards review queue.
 */
import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(DIR, 'node_modules/ts-fsrs/package.json'), 'utf8'));

await esbuild.build({
  stdin: {
    contents: "export * from 'ts-fsrs';",
    resolveDir: DIR,
  },
  bundle: true,
  format: 'iife',
  globalName: 'TSFSRS',
  minify: true,
  outfile: path.join(DIR, 'vendor/ts-fsrs.js'),
  banner: {
    js: `/* ts-fsrs v${pkg.version} (MIT) — https://github.com/open-spaced-repetition/ts-fsrs\n * Generated by scripts/build-vendor.mjs — do not edit by hand. */`,
  },
});

const out = path.join(DIR, 'vendor/ts-fsrs.js');
console.log(`vendor/ts-fsrs.js — ${(fs.statSync(out).size / 1024).toFixed(1)} KB (ts-fsrs v${pkg.version})`);
